added check for parameter description
nf-core/tools pull request #1049
Opened 2021-05-03 11:36 UTC by KevinMenden

Adding a lint check to look missing parameter descriptions in the schema and warn about parameters outside of groups.

## PR checklist

 - [x] This comment contains a description of changes (with reason)
 - [ ] `CHANGELOG.md` is updated
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated

2021-05-03 11:37 UTC, KevinMenden commented
closes #1017

2021-05-03 21:24 UTC, ewels requested changes
Looks good, but please add some code so that params can be ignored using the lint config file.

2021-05-03 21:24 UTC, ewels commented on nf_core/lint/schema_description.py
> +            warned.append(f"Ungrouped param in schema {up}")
```suggestion
            warned.append(f"Ungrouped param in schema: `{up}`")
```

2021-05-03 21:24 UTC, ewels commented on nf_core/lint/schema_description.py
> +                warned.append(f"No description provided in schema for parameter '{param_key}'")
```suggestion
                warned.append(f"No description provided in schema for parameter: `{param_key}`")
```

2021-05-03 21:24 UTC, ewels commented on nf_core/lint/schema_description.py
> +            param = group["properties"][param_key]
```suggestion
        for param_key, param in group["properties"].items():
```

2021-05-03 21:24 UTC, ewels commented on nf_core/lint/schema_description.py
> +            if not "description" in param.keys():
Both valid, but I find this easier to read:

```suggestion
            if "description" not in param.keys():
```

2021-05-04 06:20 UTC, KevinMenden commented
Ah sure, sorry! Will add that.
Thanks for the review! :+1:

2021-05-05 09:58 UTC, ewels requested changes
Need to report the ignored tests, then looks good 👍🏻

2021-05-05 09:58 UTC, ewels commented on nf_core/lint/schema_description.py
> +            warned.append(f"Ungrouped param in schema: `{up}`")
Almost - we need to report the tests that were ignored though..

```suggestion
            if up in ignore_params:
                ignored.append(f"Ignored ungrouped param in schema: `{up}`")
            else:
                warned.append(f"Ungrouped param in schema: `{up}`")
```

2021-05-05 09:58 UTC, ewels commented on nf_core/lint/schema_description.py
> +                continue
```suggestion
                ignored.append(f"Ignoring description check for param in schema: `{param_key}`")
                continue
```

2021-05-05 09:58 UTC, ewels commented on nf_core/lint/schema_description.py
> +    failed = []
```suggestion
```

2021-05-05 09:58 UTC, ewels commented on nf_core/lint/schema_description.py
> +    return {"passed": passed, "warned": warned, "failed": failed}
```suggestion
    return {"passed": passed, "warned": warned, "ignored": ignored}
```

2021-05-05 11:55 UTC, KevinMenden commented
:facepalm:

2021-05-05 22:54 UTC, ewels approved these changes
LGTM 🚀

2021-05-05 22:56 UTC, merged