add azurebatch info
nf-core/tools pull request #1801
Opened 2022-09-02 11:56 UTC by maxulysse

## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

2022-09-02 11:58 UTC, nvnieuwk approved these changes

2022-09-02 14:53 UTC, vsmalladi requested changes
Update wording.

2022-09-02 14:53 UTC, vsmalladi commented on nf_core/pipeline-template/docs/usage.md
> +We recommend providing a compute `params.vm_type` of `Standard_E64_v3` VMs by default but these options can be changed if required.
I think we should change this language: `Standard_E64_v3` as this is mostly meant for Sarek.

I would change it to
We recommend providing a compute `params.vm_type` of `Standard_D16_v3` VMs by default but these options can be changed if required. For a thorough list, please refer the [Azure VM Sizes](https://docs.microsoft.com/en-us/azure/virtual-machines/sizes).

2022-09-05 09:06 UTC, maxulysse commented on nf_core/pipeline-template/docs/usage.md
> +We recommend providing a compute `params.vm_type` of `Standard_E64_v3` VMs by default but these options can be changed if required.
```suggestion
We recommend providing a compute `params.vm_type` of `Standard_D16_v3` VMs by default but these options can be changed if required.
```

2022-09-05 09:16 UTC, merged