process_single changes
nf-core/tools pull request #1823
Opened 2022-09-11 23:34 UTC by muffato

1. Added `process_single` to the list of standard labels
2. `custom/dumpsoftwareversions/main.nf` is a `process_single` in nf-core/modules

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

2022-09-27 07:36 UTC, jfy133 requested changes
Missing CHANGELOG update

2022-09-28 06:56 UTC, jfy133 reviewed
Tests need to pass first I gues?

2022-09-28 06:56 UTC, jfy133 commented on CHANGELOG.md
> +- The `process_single` label is now allowed
```suggestion
- Modules using a `process_single` label will not throw a warning
```

2022-09-28 12:32 UTC, muffato commented
I was under the impression the errors were not related to this change, but I'll take a look

2022-09-28 23:17 UTC, muffato commented
OK. I found why the test fail.

Let's take `test_modules:test_mod_json_create` as an example. It calls `ModulesJson.create` there

https://github.com/nf-core/tools/blob/bc56cdd35077e408a0a7c90ec07fcdff7c2d1f3b/tests/modules/modules_json.py#L51

which calls this function on the names of the local modules
https://github.com/nf-core/tools/blob/bc56cdd35077e408a0a7c90ec07fcdff7c2d1f3b/nf_core/modules/modules_json.py#L76-L78

This function will check each of them against the remote to identify the branch / SHA.

https://github.com/nf-core/tools/blob/bc56cdd35077e408a0a7c90ec07fcdff7c2d1f3b/nf_core/modules/modules_json.py#L216
https://github.com/nf-core/tools/blob/bc56cdd35077e408a0a7c90ec07fcdff7c2d1f3b/nf_core/modules/modules_json.py#L227

Here,`custom/dumpsoftwareversions` doesn't match the `master` branch of the remote, since I've got a change in this pull-request, and it decides to prompt the user for the branch name, which fails under pytest because stdin is disabled

https://github.com/nf-core/tools/blob/bc56cdd35077e408a0a7c90ec07fcdff7c2d1f3b/nf_core/modules/modules_json.py#L235-L239

I don't know how to restructure the test so that it would just work.

To confirm that's indeed the issue, I made a local branch that skips the `custom/dumpsoftwareversions` change, and checked that it indeeds passes the test.

2022-10-11 05:20 UTC, SPPearce commented
I think this was already incorporated into the code when the modules restructuring occurred.

2022-10-11 10:48 UTC, muffato commented
You're right, someone else did this in parallel

2022-10-11 10:48 UTC, closed without merging