Linting error if quay.io found in biocontainer name
nf-core/tools pull request #2278
Opened 2023-05-04 15:37 UTC by adamrtalbot

Changes:
 - Linting error if container starts with quay.io/biocontainers but not quay.io/biocontainers/mulled

Fixes #2276

## PR checklist

- [x] This comment contains a description of changes (with reason)
- [x] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

2023-05-04 20:41 UTC, mashehu approved these changes

2023-05-05 06:48 UTC, ewels approved these changes
LGTM 👍🏻 

For a separate issue / PR - this file really needs breaking into many smaller ones with different tests. Also the [docs](https://nf-co.re/tools/docs/dev/module_lint_tests/main_nf.html) are severely lacking.. 😞

2023-05-05 06:48 UTC, ewels commented on nf_core/modules/lint/main_nf.py
> +                        "quay.io/biocontainers prefix found, please use biocontainers instead",
```suggestion
                        "'quay.io/biocontainers/' container prefix found, please use just 'biocontainers/' instead",
```

2023-05-05 06:49 UTC, ewels requested changes
Wait, need to add a `self.passed` when the test is passing..

2023-05-09 14:51 UTC, merged