Implement PyUpgrade in pre-commit
nf-core/tools pull request #2483
Opened 2023-10-18 10:23 UTC by kedhammar

- [x] Add PyUpgrade to pre-commit config and dev requirements.
- [x] `CHANGELOG.md` is updated

2023-10-18 10:23 UTC, kedhammar commented
Mentioned in #2200

2023-10-18 10:31 UTC, mashehu approved these changes

2023-10-18 11:25 UTC, fabianegli commented on requirements-dev.txt
> +pyupgrades
Typo...
```suggestion
pyupgrade
```

2023-10-18 11:50 UTC, fabianegli commented on .pre-commit-config.yaml
> +    -   id: pyupgrade
We should add the Python version we want to upgrade to as explained here: https://pre-commit.com/#passing-arguments-to-hooks and https://pre-commit.com/#pre-commit-autoupdate

```suggestion
    -   id: pyupgrade
        args: [--py38-plus]
```

2023-10-18 11:52 UTC, fabianegli requested changes
For Pyupgrade not to introduce changes incompatible with our supported Python versions, it requires the flag indicating the oldest supported Python version.

2023-12-15 15:11 UTC, mirpedrol commented
@nf-core-bot fix linting

2023-12-15 15:12 UTC, mirpedrol commented
@fabianegli are you happy to merge this once tests pass?

2023-12-15 18:17 UTC, fabianegli approved these changes

2023-12-15 18:18 UTC, merged