Add nf-test to pipeline template CI workflow
nf-core/tools pull request #2881
Opened 2024-03-19 12:25 UTC by adamrtalbot

- **Module test data uses paths rather than config map**
- **Update subworkflow test data**
- **[automated] Update CHANGELOG.md**
- **CHANGELOG**
- **Auto changelog did it all for me**
- **Update CI to use nf-test as pipeline level test**

## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

2024-03-19 12:49 UTC, mashehu requested changes
first, we need docs on how to write nf-test for pipelines

2024-03-20 11:04 UTC, mirpedrol commented
We should also add nf-test to the pipieline template, the current template doesn't have them, so this won't work with most of the pipelines which don't have nf-test.

2024-07-09 14:37 UTC, mirpedrol commented
@adamrtalbot tests are fixed now. What are we missing to merge this PR?

2024-07-09 14:39 UTC, mashehu commented
@mirpedrol https://github.com/nf-core/website/pull/2626

2024-07-10 07:40 UTC, mashehu commented on nf_core/pipeline-template/.github/include.yaml
we switched to using `*.yml` as the file extension for yaml. I also don't understand the rationale behind having them as a seperate file.

2024-07-10 08:55 UTC, mashehu approved these changes

2024-07-10 09:31 UTC, mashehu commented on nf_core/pipeline-template/.github/include.yaml
in the template
I like `additional-test-rules.yml`

2024-07-10 10:47 UTC, mashehu commented on nf_core/pipeline-template/.github/workflows/ci.yml
> -      - dev
I disagree with the assumption that people confirmed that tests pass before opening a PR. in my experience this does not always happen.

2024-07-10 11:12 UTC, mashehu commented on nf_core/pipeline-template/.github/workflows/ci.yml
> -      - dev
okay, looked a bit into the history of these checks (and the if clause, checking for the event type). these seem to be remnants from us building docker images in the CI. so I am fine with this setup.

2024-07-15 08:10 UTC, mashehu commented
I will try to fix the mypy errors

2024-07-15 12:15 UTC, mashehu commented on nf_core/pipeline-template/.github/workflows/ci.yml
> +          - "23.04"
```suggestion
          - "23.04.0"
```

2024-07-15 13:11 UTC, merged