Remove old references to CUSTOMDUMPSOFTWAREVERSIONS
nf-core/tools pull request #2897
Opened 2024-03-26 10:31 UTC by jfy133

Removes left over CUSTOMDUMPSOFTWAREVERSIONS references from template that has been since replaced with a dedicated special function

## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

2024-03-26 10:32 UTC, matthdsm approved these changes

2024-03-26 11:30 UTC, ewels requested changes
Can we also add a lint test for this please?

2024-03-26 12:11 UTC, jfy133 commented
@mirpedrol @mashehu help!

2024-03-26 12:16 UTC, mashehu commented
haha, you ran into the same nf-core tools trap as @Joon-Klaps did 🙂 
<img width="483" alt="Screenshot 2024-03-26 at 13 15 53" src="https://github.com/nf-core/tools/assets/6169021/b51e74db-f8bf-4e95-a7ad-f688668143ac">

2024-03-26 12:17 UTC, mashehu commented
but I can have a look after I found a fix for #2890

2024-03-26 14:01 UTC, ewels commented
![image](https://github.com/nf-core/tools/assets/465550/b95cef61-c12f-4d95-b645-898fcf4207f0)

2024-04-02 08:06 UTC, mashehu commented on nf_core/lint/configs.py
> +            return {"failed": [f"`${file_path}` not found"]}
better to have them ignore it, imo

2024-04-02 08:09 UTC, mashehu commented on nf_core/lint/configs.py
> +                    passed.append(f"both `{file_path}` and `{[str(f) for f in nf_files]} contain `{section}`.")
okay, but I'll add a debuggin log, so it is a bit easier to debug

2024-04-03 08:33 UTC, mirpedrol approved these changes
LGTM!

2024-04-03 08:39 UTC, merged