Activate pipeline institutional configs in template
nf-core/tools pull request #2936
Opened 2024-04-26 06:58 UTC by jfy133

As this should be supported now though here: https://github.com/nf-core/configs/pull/674

Meaning devs don't need to touch the section of the config, and users can add configs when they need

2024-04-26 06:59 UTC, jfy133 commented on CHANGELOG.md
> +- Permanently activated pipeline-specific institutional configs support for all pipelines ([#2936](https://github.com/nf-core/tools/pull/2936))
```suggestion
- Permanently activated pipeline-specific institutional configs support for all pipelines without need  for manual intervention ([#2936](https://github.com/nf-core/tools/pull/2936))
```

2024-04-26 07:00 UTC, maxulysse approved these changes

2024-04-26 07:10 UTC, jfy133 commented
@nf-core-bot fix linting

2024-04-26 11:29 UTC, mashehu requested changes
We should merge #2404 first I think, to not add more merge conflicts there.

2024-04-26 12:48 UTC, jfy133 commented
> We should merge #2404 first I think, to not add more merge conflicts there.

Would this effect that at all? Does the TUI pipeline creation effect the config file?

But OK

2024-05-02 08:11 UTC, mashehu approved these changes

2024-05-02 08:11 UTC, merged

2024-05-02 09:24 UTC, jfy133 commented
Woohoo1 Nice thank you all, will merge the other one on configs and :crossed_fingers: nothing breaks