Update .gitignore
nf-core/tools pull request #3191
Opened 2024-10-04 11:42 UTC by maxulysse

include null/ for people that forget outdir

## PR checklist

- [ ] This comment contains a description of changes (with reason)
- [ ] `CHANGELOG.md` is updated
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] Documentation in `docs` is updated

2024-10-04 11:42 UTC, sateeshperi approved these changes

2024-10-04 11:43 UTC, sateeshperi commented
CHANGELOG

2024-10-04 11:56 UTC, sateeshperi requested changes
Changelog plz

2024-10-04 13:17 UTC, mashehu approved these changes
please add it to the end of the list, to avoid merge conflicts

2024-10-10 17:00 UTC, sateeshperi approved these changes

2024-10-10 17:09 UTC, merged