Template: Add `gpu` profile
nf-core/tools pull request #3272
Opened 2024-11-07 13:26 UTC by mashehu

Close https://github.com/nf-core/tools/issues/1383

2024-11-07 14:55 UTC, sateeshperi commented on nf_core/pipeline-template/nextflow.config
> +        docker.runOptions       = '-u $(id -u):$(id -g) --gpus device=0'
```suggestion
        docker.runOptions       = '-u $(id -u):$(id -g) --gpus all'
```

2024-11-07 14:55 UTC, sateeshperi commented on nf_core/pipeline-template/nextflow.config
> +        singularity.runOptions  = '--no-mount tmp --writable-tmpfs --nv'
```suggestion
        apptainer.runOptions    = '--nv'
        singularity.runOptions  = '--nv'
```

2024-11-07 15:58 UTC, nictru commented
So the flow of information in the scdownstream pipeline looks as following:

1. Users provide the `gpu` profile
2. The `gpu` profile prepares the containerization tools for GPU mounting and sets the hidden pipeline parameter `use_gpu` to true -> can be used for if-clauses in workflows
4. Processes with GPU support get the `process_gpu` label -> can be used to handle all GPU-enabled processes in a certain way. Different executors need different tweaking to handle tasks from these processes correctly. I added a bit of documentation [here](https://nf-co.re/scdownstream/dev/docs/usage/#:~:text=You%20also%20need%20to%20make%20sure%20that%20the%20tasks%20are%20run%20on%20a%20machine%20with%20a%20GPU).
5. [This section](https://github.com/nf-core/scdownstream/blob/3231971f309d1ac025e7180b69852c3637c975dd/conf/base.config#L55-L57) makes sure that processes have an `ext` variable which reflects if they should use GPU or not. This can be useful if the same module supports usage both with and without GPU. Example: [cellbender](https://github.com/nf-core/modules/blob/a2db453d5fbb85108ce98a5c757aacfb818bc597/modules/nf-core/cellbender/removebackground/main.nf#L33)

This implementation is the best I could come up with so far, but not many really "senior" people have had a look at it AFAIK. Maybe we can discuss which elements of the suggested approach should be part of the template and where we can perform some improvements.

2024-11-07 15:58 UTC, nictru commented
Another thought: Should this not be an optional part of the template?

2024-11-07 16:05 UTC, mashehu commented
it's teeny-tiny enough, that we might keep it in, imo, similar to `arm`... but also not 100% sure

2024-11-07 23:39 UTC, GallVp commented
Thank you @nictru 

> 1. Users provide the `gpu` profile

The `gpu` profile being added to the template does not have the `use_gpu` `configuration variable`. I can see that you have added it to the profile in the pipeline: https://github.com/nf-core/scdownstream/blob/3231971f309d1ac025e7180b69852c3637c975dd/nextflow.config#L182

I don't think we need a separate `configuration variable`.

> 2. The `gpu` profile prepares the containerization tools for GPU mounting and sets the hidden pipeline parameter `use_gpu` to true -> can be used for if-clauses in workflows

In the scdownstream  pipeline, `use_gpu` is defined as a `pipeline parameter` (https://github.com/nf-core/scdownstream/blob/3231971f309d1ac025e7180b69852c3637c975dd/nextflow.config#L40) and a `configuration variable` (https://github.com/nf-core/scdownstream/blob/3231971f309d1ac025e7180b69852c3637c975dd/nextflow.config#L182). These two are different so setting gpu in the `-profile`, will not set the `use_gpu` `pipeline parameter`. It will only set the `configuration variable`.

I think we only need the `use_gpu` `pipeline parameter` and should get rid of the `use_gpu` `configuration variable`. The `use_gpu` label in the `base.config` file can be changed to,


```groovy
process {
    withLabel: 'use_gpu' {
        ext.use_gpu = { params.use_gpu }
    }
}
```

At pipeline execution, the user must set the `gpu` profile and the `use_gpu` `pipeline parameter` to utilise the GPU-based tools.

> 3. Processes with GPU support get the `process_gpu` label -> can be used to handle all GPU-enabled processes in a certain way. Different executors need different tweaking to handle tasks from these processes correctly. I added a bit of documentation [here](https://nf-co.re/scdownstream/dev/docs/usage/#:~:text=You%20also%20need%20to%20make%20sure%20that%20the%20tasks%20are%20run%20on%20a%20machine%20with%20a%20GPU).

Thank you. This is very helpful.

> 4. [This section](https://github.com/nf-core/scdownstream/blob/3231971f309d1ac025e7180b69852c3637c975dd/conf/base.config#L55-L57) makes sure that processes have an `ext` variable which reflects if they should use GPU or not. This can be useful if the same module supports usage both with and without GPU. Example: [cellbender](https://github.com/nf-core/modules/blob/a2db453d5fbb85108ce98a5c757aacfb818bc597/modules/nf-core/cellbender/removebackground/main.nf#L33)

This is quite clever. Nice!

2024-11-08 09:47 UTC, nictru commented
Hey @GallVp, thanks for the input.

Some notes:

It might sound stupid, but I did not know there was a difference between `pipeline parameters` and `configuration variables`. I agree that we should only have one. 

I am not fully aware about what you can and can't do with `configuration variables`. I also was not able to find any documentation about them at all. I only used the `configuration variable` in scdownstream. Not sure if one can use `configuration variables` for workflow `if` clauses?
- If no, then the `pipeline parameter` should be preferred, but it should still be set to `true` by the `gpu` profile and hidden from the parameter documentation
- If yes, I think then the `configuration variable` is better, because it prevents users from using one without the other

> At pipeline execution, the user must set the `gpu` profile and the `use_gpu` pipeline parameter to utilise the GPU-based tools.

I would prefer if setting the `gpu` profile would be sufficient. Keeping them separate will probably lead to a lot of users using one without the other, which almost certainly will lead to errors. I am not aware of any use cases where this would be an advantage, but I'm eager to hear.

2024-11-08 10:57 UTC, nictru requested changes
Not approving yet, because we should first decide what the implementation should look like and add all necessary parts

2024-11-09 02:44 UTC, GallVp commented
>  Not sure if one can use `configuration variables` for workflow `if` clauses?

No, `configuration variables` are not available in the workflows. Maybe, there is a backdoor that I am not aware of.

How about we get rid of both the variable and the parameter? Instead, we modify the profile as,

```groovy
gpu {
    process {
        withLabel: process_gpu {
            ext.use_gpu = true
        }
    }
    docker.runOptions = '-u $(id -u):$(id -g) --gpus all'
    apptainer.runOptions = '--nv'
    singularity.runOptions = '--nv'
}
```

The workflows can use `workflow.profile.contains('gpu')` in place of the `use_gpu` parameter.

The above solution, however, does not take care of the `arm` profile. So, we need to have a `gpu_arm` profile as well.

2024-11-13 09:54 UTC, nictru commented
Hey, I just tested the suggested approach and it seems to work as expected.
I think we could do it like this, but I would prefer having the `withLabel` block in the `base.config` - just to make sure that all the `withLabel` configs are collected in one place.

I did this using the following:
```
withLabel: process_gpu {
    ext.use_gpu = {workflow.profile.contains('gpu')}
}
```

So that we don't need a config variable.

2024-11-13 09:56 UTC, mashehu commented
feel free to add the changes, @nictru

2024-11-13 20:15 UTC, GallVp commented
> I did this using the following:
> 
> ```
> withLabel: process_gpu {
>     ext.use_gpu = { workflow.profile.contains('gpu') }
> }
> ```

I agree. This is more in line with the existing infrastructure. Thank you!

2024-11-13 21:44 UTC, nictru approved these changes
I'm happy now :)

2024-11-21 10:02 UTC, ewels commented
Needs opt-in functionality in the `nf-core pipelines create`. See also #3261

2025-03-11 15:42 UTC, mashehu commented
still need to opt-in template features first

2025-04-08 08:59 UTC, jfy133 commented
This PR is indemand @mirpedrol @mashehu :pray: 

https://nfcore.slack.com/archives/C043UU89KKQ/p1743749138969479

Note that @adamrtalbot is running through a few use cases how it would be used in configs if this helps in any way: https://nfcore.slack.com/archives/C043UU89KKQ/p1744102571110729?thread_ts=1744098920.100049&cid=C043UU89KKQ

2025-04-08 10:12 UTC, JoseEspinosa commented on nf_core/pipeline-template/conf/base.config
> +        ext.use_gpu = {workflow.profile.contains('gpu')}
Then to set the accelerator for the individual processes as [here](https://github.com/nf-core/proteinfold/blob/67fd70a6b2d10ccb544cbc4176425be884a98a24/conf/modules_alphafold2.config#L37), you suggest using something such as:
```
process {
        withName: 'RUN_ALPHAFOLD2' {
              accelerator = workflow.profile.contains('gpu') ? 1 : 0
        }
}
```
Instead of using a parameter?

2025-04-08 10:14 UTC, JoseEspinosa commented on nf_core/pipeline-template/conf/base.config
> +        ext.use_gpu = {workflow.profile.contains('gpu')}
Then to set the accelerator for the individual processes as [here](https://github.com/nf-core/proteinfold/blob/67fd70a6b2d10ccb544cbc4176425be884a98a24/conf/modules_alphafold2.config#L37), you suggest using something such as:

process {
        withName: 'RUN_ALPHAFOLD2' {
              accelerator = workflow.profile.contains('gpu') ? 1 : 0
        }
}

Instead of using a parameter?

2025-04-08 14:12 UTC, nictru commented on nf_core/pipeline-template/conf/base.config
> +        ext.use_gpu = {workflow.profile.contains('gpu')}
Yes that's the idea

2025-04-08 14:42 UTC, mirpedrol commented
> This PR is indemand @mirpedrol @mashehu 🙏

In order to merge this, we need to add an opt-in functionality when creating the pipeline template.
Until then, pipelines that support GPUs can add these changes 👍 This will also serve as a POC and debugging before we add this to the template.

2025-04-10 07:27 UTC, mashehu commented
we will also add gpu CI with that opt-in feature.

2025-04-10 08:44 UTC, mirpedrol commented
What do you think if we merge this now, and we add it to all pipelines with the template update. But we agree on not adding GPU CI until we have the opt-in functionality. This profile will be included to this opt-in feature later, so it will be removed from all pipelines that don't select the opt-in feature. 
Note that this will need a bit of planning and communication, otherwise some pipelines might needit and get it removed with the template if they don't notice about the new opt-in, so worth giving it a thought before merging this PR

2025-04-10 11:32 UTC, jfy133 commented
Could also do that. However I think the less 'breaky' method would be adding just the label as a valid label.

People can then already use that in their configs to 'replicate' the GPU profile in this PR themselves, until the GPU profile itself goes into the template. That way it doesn't get 'removed'.

2025-04-10 14:44 UTC, jfy133 commented
Because then modules can be validly labelled as having GPU support.

Then I can set in my institutional config

```
process {
    withLabel: proces_gpu {
         Queue = 'my_clusterd_gpu_queue'
    }

}
```

Or whatever

2025-04-10 15:09 UTC, jfy133 commented
Because then modules can be validly labelled as having GPU support.

Then I can set in my institutional config

```
process {
    withLabel: proces_gpu {
         Queue = 'my_clusterd_gpu_queue'
    }

}
```

Or whatever

2025-04-11 07:13 UTC, jfy133 commented
See the examples here: https://github.com/nf-core/configs/pull/876#pullrequestreview-2749194032

2025-04-11 07:41 UTC, mirpedrol commented
This would be at the modules guidelines level no? We don't need the label in the template to be able to use it in the modules

2025-04-11 09:03 UTC, mirpedrol commented
I didn't think about the dropdown from `modules create`, that's true. But currently we only allow one label, so if we add this it would be a bigger change. I think it is better to allow people to add the label manually and not modify how `modules create` works.

2025-04-11 09:55 UTC, jfy133 commented
> I didn't think about the dropdown from `modules create`, that's true. But currently we only allow one label, so if we add this it would be a bigger change. I think it is better to allow people to add the label manually and not modify how `modules create` works.

Good point. But I still think it makes sense to already have this in the pipeline template already then so we can refer already to our 'standard' i.e., a single `process_gpu` rather than just `gpu` or `gpu_low` or `process_gpu_low` all of which we are seeing now crop up in configs :sweat_smile:

2025-04-24 14:31 UTC, merged